### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by vicLeva** [frankandreace/cqf_implementation#5]
https://github.com/frankandreace/cqf_implementation/blob/ceb2b6aa97834a65f24fa0a10c5ee3cd387fe0d9/cqf/filter.cpp#L778
https://github.com/frankandreace/cqf_implementation/blob/0f9795bd4ddb8e1c1b2dfee98356719ed3249a83/cqf/filter.cpp#L719
https://github.com/frankandreace/cqf_implementation/blob/0f9795bd4ddb8e1c1b2dfee98356719ed3249a83/cqf/filter.cpp#L720  
  
With the random_uints binary, I tried with 20+k values. At some point with some seeds, I reach an infinite while loop because `curr_quotient` and `rend_pos` are being stucked with the same values.

cmd after build :   
`./bin/random_uints -n 21000 -v -r 3`   
  
result :  
```insertions 20872/21000
quot 510079
rem 28110235544823
FUS curr_quotient 510079
FUS out of sel_rank 510079
curr_quot 510080
rend_pos 510079
curr_quot 510080
rend_pos 510079
curr_quot 510080
rend_pos 510079
curr_quot 510080
rend_pos 510079```

**Comment by frankandreace** [comment]
Yes I already saw the bug. Will release a patch soon.

**Comment by frankandreace** [comment]
The issue has been solved
